/** Auth-related cookie names that indicate a usable YouTube session for yt-dlp. */
export const YT_AUTH_COOKIE_NAMES = [
  'SID',
  'HSID',
  'SSID',
  'APISID',
  'SAPISID',
  '__Secure-1PSID',
  '__Secure-3PSID',
  'LOGIN_INFO',
];

/**
 * Fetch YouTube cookies from the browser session.
 * Requires the "cookies" permission and host access to youtube.com.
 */
export async function getYoutubeCookies() {
  if (!chrome?.cookies?.getAll) {
    throw new Error('Cookie API unavailable — reload the extension after updating permissions.');
  }

  const cookies = await chrome.cookies.getAll({ domain: 'youtube.com' });
  return [...cookies].sort((a, b) => {
    const domainCmp = a.domain.localeCompare(b.domain);
    if (domainCmp !== 0) return domainCmp;
    return a.name.localeCompare(b.name);
  });
}

/**
 * Convert chrome.cookies entries to Netscape cookies.txt (yt-dlp --cookies format).
 */
export function toNetscapeCookieFile(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.haxx.se/rfc/cookie_spec.html',
    '# This file was generated by Aether for yt-dlp. Do not commit.',
    '',
  ];

  for (const cookie of cookies) {
    const domain = cookie.hostOnly
      ? cookie.domain.replace(/^\./, '')
      : cookie.domain.startsWith('.')
        ? cookie.domain
        : `.${cookie.domain}`;
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.session
      ? '0'
      : String(Math.floor(cookie.expirationDate || 0));
    const value = String(cookie.value ?? '').replace(/[\t\r\n]/g, '');
    lines.push(
      [domain, includeSubdomains, cookie.path || '/', secure, expiry, cookie.name, value].join('\t')
    );
  }

  return `${lines.join('\n')}\n`;
}

export function summarizeYoutubeCookies(cookies) {
  const names = new Set(cookies.map((c) => c.name));
  const presentAuth = YT_AUTH_COOKIE_NAMES.filter((name) => names.has(name));
  const missingAuth = YT_AUTH_COOKIE_NAMES.filter((name) => !names.has(name));
  const sessionCount = cookies.filter((c) => c.session).length;
  const soonestExpiry = cookies
    .filter((c) => !c.session && typeof c.expirationDate === 'number')
    .map((c) => c.expirationDate)
    .sort((a, b) => a - b)[0];

  return {
    total: cookies.length,
    presentAuth,
    missingAuth,
    sessionCount,
    soonestExpiry: soonestExpiry ?? null,
    looksSignedIn: presentAuth.length >= 3 || names.has('LOGIN_INFO'),
  };
}

export function formatCookieExpiry(cookie) {
  if (cookie.session) return 'Session';
  if (!cookie.expirationDate) return 'Unknown';
  return new Date(cookie.expirationDate * 1000).toLocaleString();
}

export function maskCookieValue(value, reveal = false) {
  if (reveal) return value || '';
  if (!value) return '';
  if (value.length <= 8) return '••••••••';
  return `${value.slice(0, 4)}…${value.slice(-4)}`;
}

/**
 * Trigger a browser download of Netscape youtube_cookies.txt.
 */
export function downloadNetscapeCookies(cookies, filename = 'youtube_cookies.txt') {
  const body = toNetscapeCookieFile(cookies);
  const dataUrl = `data:text/plain;charset=utf-8,${encodeURIComponent(body)}`;

  return new Promise((resolve, reject) => {
    chrome.downloads.download(
      {
        url: dataUrl,
        filename,
        saveAs: true,
      },
      (downloadId) => {
        if (chrome.runtime.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(downloadId);
      }
    );
  });
}
